# Generated by Django 4.2.11 on 2025-01-02 10:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firefighters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.CharField(choices=[('Director', 'Director'), ('Chief Superintendent', 'Chief Superintendent'), ('Senior Superintendent', 'Senior Superintendent'), ('Superintendent', 'Superintendent'), ('Chief Inspector', 'Chief Inspector'), ('Senior Inspector', 'Senior Inspector'), ('Inspector', 'Inspector')], help_text="Firefighter's rank", max_length=45)),
                ('experience_level', models.CharField(choices=[('Probationary Firefighter', 'Probationary Firefighter'), ('Firefighter I', 'Firefighter I'), ('Firefighter II', 'Firefighter II'), ('Firefighter III', 'Firefighter III'), ('Driver', 'Driver'), ('Captain', 'Captain'), ('Battalion Chief', 'Battalion Chief')], help_text="Firefighter's experience level", max_length=45)),
                ('station', models.CharField(choices=[('Station 1', 'Station 1'), ('Station 2', 'Station 2'), ('Station 3', 'Station 3'), ('Station 4', 'Station 4'), ('Station 5', 'Station 5')], default='Station 1', help_text='Fire station where the firefighter is assigned', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FireStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_time', models.DateTimeField(blank=True, help_text='Date and time when the incident occurred', null=True)),
                ('severity_level', models.CharField(choices=[('Minor Fire', 'Minor Fire'), ('Moderate Fire', 'Moderate Fire'), ('Major Fire', 'Major Fire')], help_text='Level of fire severity', max_length=45)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resolve', 'Resolve')], default='Active', max_length=45)),
                ('description', models.TextField(help_text='Detailed description of the incident', max_length=1000)),
                ('incident_type', models.CharField(blank=True, choices=[('Structure Fire', 'Structure Fire'), ('Vehicle Fire', 'Vehicle Fire'), ('Wildfire', 'Wildfire'), ('Chemical Fire', 'Chemical Fire'), ('Electrical Fire', 'Electrical Fire')], help_text='Type of fire incident', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, help_text='Latitude coordinate of the location', max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, help_text='Longitude coordinate of the location', max_digits=22, null=True)),
                ('address', models.CharField(blank=True, help_text='Full address from geocoding', max_length=500)),
                ('city', models.CharField(blank=True, help_text='City name', max_length=150)),
                ('country', models.CharField(blank=True, help_text='Country name', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weather_description', models.CharField(max_length=150)),
                ('wind_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.incident')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fire.locations'),
        ),
        migrations.CreateModel(
            name='FireTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(default='Unknown Truck Number', max_length=150, unique=True)),
                ('model', models.CharField(default='Unknown Model', max_length=150)),
                ('capacity', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)])),
                ('station', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fire.firestation')),
            ],
            options={
                'verbose_name': 'Fire Truck',
                'verbose_name_plural': 'Fire Trucks',
                'ordering': ['truck_number'],
            },
        ),
    ]
