# Generated by Django 4.2.11 on 2024-11-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Contained', 'Contained'), ('Extinguished', 'Extinguished')], default='Active', max_length=45),
        ),
    ]
