# Generated by Django 4.2.11 on 2024-11-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_incident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(blank=True, choices=[('Structure Fire', 'Structure Fire'), ('Vehicle Fire', 'Vehicle Fire'), ('Wildfire', 'Wildfire'), ('Chemical Fire', 'Chemical Fire'), ('Electrical Fire', 'Electrical Fire')], help_text='Type of fire incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='experience_level',
            field=models.CharField(choices=[('Probationary Firefighter', 'Probationary Firefighter'), ('Firefighter I', 'Firefighter I'), ('Firefighter II', 'Firefighter II'), ('Firefighter III', 'Firefighter III'), ('Driver', 'Driver'), ('Captain', 'Captain'), ('Battalion Chief', 'Battalion Chief')], help_text="Firefighter's experience level", max_length=45),
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firefighters', to='fire.firestation'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date_time',
            field=models.DateTimeField(blank=True, help_text='Date and time when the incident occurred', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(help_text='Detailed description of the incident', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fire.locations'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity_level',
            field=models.CharField(choices=[('Minor Fire', 'Minor Fire'), ('Moderate Fire', 'Moderate Fire'), ('Major Fire', 'Major Fire')], help_text='Level of fire severity', max_length=45),
        ),
    ]
