# Generated by Django 4.2.11 on 2025-01-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0005_locations_municipality_locations_neighborhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firefighters',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='firefighters',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='firestation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='firestation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='firestation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='firestation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='firetruck',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='firetruck',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='province',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='street',
        ),
        migrations.RemoveField(
            model_name='weatherconditions',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weatherconditions',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='rank',
            field=models.CharField(choices=[('Director', 'Director'), ('Chief Superintendent', 'Chief Superintendent'), ('Senior Superintendent', 'Senior Superintendent'), ('Superintendent', 'Superintendent'), ('Chief Inspector', 'Chief Inspector'), ('Senior Inspector', 'Senior Inspector'), ('Inspector', 'Inspector')], help_text="Firefighter's rank", max_length=45),
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='station',
            field=models.CharField(choices=[('Station 1', 'Station 1'), ('Station 2', 'Station 2'), ('Station 3', 'Station 3'), ('Station 4', 'Station 4'), ('Station 5', 'Station 5')], default='Station 1', help_text='Fire station where the firefighter is assigned', max_length=150),
        ),
        migrations.AlterField(
            model_name='locations',
            name='address',
            field=models.CharField(blank=True, help_text='Full address from geocoding', max_length=500),
        ),
        migrations.AlterField(
            model_name='locations',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=150),
        ),
        migrations.AlterField(
            model_name='locations',
            name='country',
            field=models.CharField(blank=True, default=1, help_text='Country name', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Latitude coordinate of the location', max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Longitude coordinate of the location', max_digits=22, null=True),
        ),
    ]
