# Generated by Django 4.2.11 on 2025-01-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0006_remove_firefighters_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='firestation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
