# Generated by Django 4.2.11 on 2025-01-02 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0007_firestation_latitude_firestation_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='firestation',
            name='address',
            field=models.CharField(blank=True, help_text='Full address from geocoding', max_length=500),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=150),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='country',
            field=models.CharField(blank=True, help_text='Country name', max_length=150),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Latitude coordinate of the location', max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Longitude coordinate of the location', max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='firestation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fire.location'),
        ),
    ]
